### ISSUE TITLE
Pickles.Powershell.dll was not loaded because no valid module file was found.......

### ISSUE THREAD

**Issue by cantillos** [x97mdr/pickles#112]
When installing Pickles via the NuGet console, I'm getting the following; 

Import-Module : The specified module C:.....blah blah....\Pickles.0.8.0.0\tools\Pickles.Powershell.dll was not loaded because no valid module file was found in any module directory.
At: C:...blah....\packages\Pickles.0.8.0.0\tools\init.ps1:3 char:14
+Import-Module <<<< (Join-Path $toolsPath Pickles.Powershell.dll) 
+CategoryInfo : ResourceUnavailable: (C:...Powershell.dll:String) [Import-Module], FileNotFoundException

It would appear to be trying to a non-existent file - sure enough when checking in the Pickles.0.8.0.0 folder, the file is not present. 
NuGet finishes by stating "Pickles Installed" but when you try the Pickle-Features cmdlet it's not recognized. 

I've managed to force it to work, by specifically importing the module PicklesDoc.Pickles.Powershell.dll

**Comment by sthiers** [comment]
same issue here:
1. Install-Package Pickles -> get error msg The specified module 'D:...\packages\Pickles.0.8.0.0\tools\Pickles.PowerShell.dll' was not loaded because no valid module file was found in any module directory.
2. Pickle-Features -> get error msg The term 'Pickle-Feature' is not recognized as the name of a cmdlet, function, script file, or operable program
3. Import-Module D:...\packages\Pickles.0.8.0.0\tools\PicklesDoc.Pickles.PowerShell.dll -> warning about unapporved verbs
4. Pickle-Features -> it works

**Comment by x97mdr** [comment]
I'm leaving town on a short vacation. I'll have a look at this next week
when I return.

**Comment by x97mdr** [comment]
Moved to picklesdoc/pickles#31

**Comment by x97mdr** [comment]
Issue was resolved.  New version of package uploaded to the NuGet gallery.  It should be available shortly
