### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by marcusoftnet** [x97mdr/pickles#39]
I think Pickles should be installed via NuGet - let's create a NuGet package. 

What do you think about the following features for it:
- Downloads all the executables (Console, MsTest, NAnt). We could also go with one package for each
- Downloads example files for each of the runners
- Creates an powershell script that you can run from the PowerShell console in Visual Studio to run the features

So - what do you think? One package or several?

**Comment by x97mdr** [comment]
I think several packages might be the better option, at least initially.  I
can't see someone using more than one type of runner for a solution.  If
they do need more than one they can just add the package for the other
runner.

I _really_ like the idea of a powershell script!  Can we create a
powershell module that calls the C# code directly rather than calling out
to the executable?  That would be really cool and help us integrate with
psake for a build tool.

A package of example files is a good start, maybe using the example project
you pointed me to earlier?

On Thu, Nov 17, 2011 at 2:29 PM, Marcus Hammarberg <
reply@reply.github.com

**Comment by x97mdr** [comment]
Pull request was merged, will generate packages tonight or tomorrow.

**Comment by marcusoftnet** [comment]
I have thought about the PowerShell version but have a hard time with it. Part because I don't speak powershell but also I'm not sure on how we want to run it. 

Should it just be a powershell command that calls into the console-app? Or should we call into the Pickles-core-dll?

**Comment by x97mdr** [comment]
I was imagining that it would be a module that calls directly into the
Pickles code.  In my opinion modules that have external dependencies add
complexity unnecessary (Is the executable there? What do we do if its not?)

I think it's fairly easy to make a new modules from a C# assembly.  I had
found a detailed guide here:
http://blogs.msdn.com/b/saveenr/archive/2010/03/08/how-to-create-a-powershell-2-0-module-and-cmdlet-with-visual-studio-2010-screencast-included.aspx
.

I threw this into a new issue here:
https://github.com/x97mdr/pickles/issues/48

What would you like to see implemented next in Pickles?

On Mon, Dec 5, 2011 at 7:45 AM, Marcus Hammarberg <
reply@reply.github.com
