### ISSUE TITLE
Autogenerate index.html

### ISSUE THREAD

**Issue by x97mdr** [x97mdr/pickles#59]
In order to view the contents of only specific sub-directories
As a user of Pickles
I want an index.html auto-generated for every sub-directory and his index.html file should be the first file listed in the sub-directory within the table of contents on the left-hand table of contents pane.

**Comment by x97mdr** [comment]
Issue was raised on the mailing list.

**Comment by dirkrombauts** [comment]
Since the nr. 1 question I get asked about Pickles at work is "what file should I open first?", I'll have a go at it.

**Comment by x97mdr** [comment]
Very true, I always put an Index.markdown at the top of my features list.
 Maybe autogenerate this only if the user hasn't provided their own
Index.markdown?

On Wed, Mar 14, 2012 at 3:07 AM, dirkrombauts <
reply@reply.github.com

**Comment by dirkrombauts** [comment]
Hi,

An update: I think I'm almost there.  We had the end-of-iteration ceremonies last week, and then I ran into trouble with relative Uris: you know, the lack of a trailing backslash in DirectoryInfo causing the Uris to think that they are files instead of directories.

I refactored the creation of Uris from FileInfos and DirectoryInfos, and then it was more or less easygoing.

The only thing missing is the "home" link at the top of the table of content.

**Comment by x97mdr** [comment]
awesome, can't wait to see it!

On Fri, Mar 30, 2012 at 10:22 AM, dirkrombauts <
reply@reply.github.com

**Comment by dirkrombauts** [comment]
OK - the "Home" link at the top of the table of content is now being generated as well.  But I'm not satisfied yet.  I made it work, but I didn't make it right yet.  So the question is how patient you are :-)

**Comment by x97mdr** [comment]
I'm very patient this week as my folks are up visiting until Saturday. :)

I'll merge this request in ASAP but I wouldn't look for it too terribly soon
